name: Deploy Locaweb via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy via Locaweb FTP
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: 'ftp.tambr.com.br'
          user: 'tambr1'  
          password: 'u4emsxF6K2PWTm!'
          localDir: .
